name: Restart Creatable Server

on: [ push ]

jobs:
  update-server:
    runs-on: ubuntu-latest 
    env:
      apiKey: ${{secrets.PTERODACTYL_PANEL_API_KEY}}
      id: ${{secrets.SERVER_ID}}
    steps:
      - name: Restart server
        run: |
          curl "https://host.snaildos.com/api/client/servers/${{env.id}}/power" \
            -H 'Accept: application/json' \
            -H 'Content-Type: application/json' \
            -H 'Authorization: Bearer ${{env.apiKey}}' \
            -X POST \
            -d '{
            "signal": "restart"
            }' 